
[origins]

	[origins."origins:enderian"]
		enabled = true
		"origins:throw_ender_pearl" = true
		"origins:water_vulnerability" = true
		"origins:pumpkin_hate" = true
		"origins:extra_reach" = true
		"origins:ender_particles" = true
		"origins:damage_from_potions" = true

	[origins."origins:arachnid"]
		enabled = true
		"origins:climbing" = true
		"origins:master_of_webs" = true
		"origins:carnivore" = true
		"origins:fragile" = true
		"origins:arthropod" = true

	[origins."origins:human"]
		enabled = true

	[origins."origins:blazeborn"]
		enabled = true
		"origins:fire_immunity" = true
		"origins:burning_wrath" = false
		"origins:hotblooded" = true
		"origins:water_vulnerability" = true
		"origins:flame_particles" = true
		"origins:damage_from_snowballs" = true
		"origins:damage_from_potions" = true

	[origins."origins:avian"]
		enabled = true
		"origins:slow_falling" = true
		"origins:fresh_air" = true
		"origins:like_air" = true
		"origins:tailwind" = true
		"origins:lay_eggs" = true
		"origins:vegetarian" = true
		"kingrace:avian/bird_wings" = true
		"kingrace:avian/feathers_for_days" = true
		"kingrace:avian/seeds_addiction" = true

	[origins."origins:feline"]
		enabled = true
		"origins:fall_immunity" = true
		"origins:nine_lives" = true
		"origins:scare_creepers" = true
		"origins:cat_vision" = true
		"origins:velvet_paws" = true

	[origins."origins:elytrian"]
		enabled = true
		"origins:elytra" = true
		"origins:aerial_combatant" = true
		"origins:more_kinetic_damage" = true
		"kingrace:elytrian/dragons_breath" = true
		"kingrace:elytrian/dragons_scales" = true
		"kingrace:elytrian/dragons_blood" = true
		"kingrace:elytrian/more_kinetic_damage" = true

	[origins."origins:shulk"]
		enabled = true
		"origins:shulker_inventory" = true
		"origins:no_shield" = true
		"origins:more_exhaustion" = true

	[origins."origins:merling"]
		enabled = true
		"origins:water_breathing" = false
		"origins:water_vision" = true
		"origins:aqua_affinity" = true
		"origins:swim_speed" = true
		"origins:like_water" = true
		"origins:aquatic" = true
		"origins:conduit_power_on_land" = true
		"origins:air_from_potions" = true
		"kingrace:merling/breathe_underwater" = true
		"kingrace:merling/water_vision" = true

	[origins."origins:phantom"]
		enabled = true
		"origins:phantomize" = true
		"origins:translucent" = true
		"origins:phasing" = true
		"origins:invisibility" = true
		"origins:burn_in_daylight" = true
		"origins:hunger_over_time" = true
		"origins:fragile" = true
		"origins:phantomize_overlay" = true

